spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning_center_db
    username: root
    password: 'Bilin1!*1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: learning_center_web_manager
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          support:
#            JdbcTransactionManager: info

logging:
  level:
    root: info


# self-defined configuration
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    bucket: learning-center-web-application



